apiVersion: apps/v1
kind: Deployment
metadata:
  name: urlshortner-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: urlshortner
  template:
    metadata:
      labels:
        app: urlshortner
    spec:
      containers:
        - name: urlshortner
          image: bpopov/urlshortner
          ports:
            - containerPort: 80
          env:
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: simpleapp
                  key: dbpass

---
apiVersion: v1
kind: Service
metadata:
  name: urlshortner
spec:
  selector:
    app: urlshortner
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80